GET http://localhost:3003/api/blogs


###

GET http://localhost:3003/api/blogs/62513b324ac840eee4d08b04

###

GET http://localhost:3003/api/blogs/62513b324ac840eee4d08b03

###

DELETE http://localhost:3003/api/blogs/6258dbd6d03b8f094c20ab60
content-type: application/json
Authorization: bearer x

###

POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer x
{
    "title": "2",
    "author": "2",
    "url": "2",
    "likes": "2"
}

###

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "1",
    "author": "1",
    "url": "1"
}

### 
PUT http://localhost:3003/api/blogs/6250cccf9d8142e0c4695541
content-type: application/json

{
    "title": "1",
    "author": "2",
    "url": "3",
    "likes":  4
}