
POST http://localhost:3003/api/login
content-type: application/json

{
    "username": "111",
    "password": "111"
}

###


POST http://localhost:3003/api/login
content-type: application/json

{
    "username": "333",
    "password": "332"
}